### ISSUE TITLE
Warnings on latest in heex templates

### ISSUE THREAD

**Issue by cadebward** [mveytsman/heroicons_elixir#7]
Hey there, thanks for this package, we love it!

I've noticed in the latest release I get a warning when using `apply`, like so:

```elixir
  @doc """
  Accepts the following attributes:

    * name
    * outlined
    * and any other HTML attribute: class, aria-label, etc

  ## Examples

      <.icon name={:home} outlined class="text-gray-400" />
      <.icon name={:home} class="text-gray-400" />
      <.icon name={:home} />
  """
  def icon(assigns) do
    assigns =
      assigns
      |> assign_new(:outlined, fn -> false end)
      |> assign_new(:class, fn -> "w-4 h-4 inline-block" end)
      |> assign_new(:"aria-hidden", fn -> !Map.has_key?(assigns, :"aria-label") end)

    ~H"""
    <%= if @outlined do %>
      <%= apply(Heroicons.Outline, @name, [assigns_to_attributes(assigns, [:outlined, :name])]) %>
    <% else %>
      <%= apply(Heroicons.Solid, @name, [assigns_to_attributes(assigns, [:outlined, :name])]) %>
    <% end %>
    """
  end
```

With the following warning:

```
warning: <%= chart_bar(class: "..." %> is deprecated, please use <.chart_bar class="..." /> inside HEEx templates instead
  (heroicons 0.3.0) lib/heroicons.ex:27: Heroicons.Outline.chart_bar/1
  (my_app 0.1.0) lib/myapp_web/live/live_helpers.ex:103: anonymous fn/2 in MyAppWeb.LiveHelpers.icon/1
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/engine.ex:124: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/engine.ex:140: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
  (my_app 0.1.0) lib/myapp_web/live/live_helpers.ex:123: anonymous fn/2 in MyAppWeb.LiveHelpers.link/1
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:515: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/4
  (elixir 1.13.2) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
  (elixir 1.13.2) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:462: Phoenix.LiveView.Diff.traverse/7
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:486: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
  (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:486: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
  (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/diff.ex:138: Phoenix.LiveView.Diff.render/3
  (phoenix_live_view 0.17.6) lib/phoenix_live_view/static.ex:244: Phoenix.LiveView.Static.to_rendered_content_tag/4
```

Downgrading to 0.2.2 removes the warning. I noticed recently there was in change in how things were generated, but I wasn't 100% sure without a changelog or commits to mark the 0.3 release. Any ideas?

**Comment by mveytsman** [comment]
I deprecated the function versions of the components in favor of the Phoenix components - which achieves what your icon wrapper does 

You can now use `<Heroicons.Outline.foo>` as a Phoenix component in your code directly 

I noted this in the readme but this is a good nudge to keep a change log and make the deprecation warning tell you what to do 

Keeping this issue to track that

**Comment by cadebward** [comment]
Oh! That's my bad for not reading better. Thanks for pointing that out and thanks for the quick response! <3

**Comment by Daniel-Xu** [comment]
> I deprecated the function versions of the components in favor of the Phoenix components - which achieves what your icon wrapper does
> 
> You can now use `<Heroicons.Outline.foo>` as a Phoenix component in your code directly
> 
> I noted this in the readme but this is a good nudge to keep a change log and make the deprecation warning tell you what to do
> 
> Keeping this issue to track that

Thanks for the response. I have a minor doubt: what if we want to reuse common class, it seems not easy to wrap  <Heroicons.Outline.foo> in a new component.

**Comment by joefreeman** [comment]
FWIW, I'd been hoping to do something like this:

```elixir
defp some_component(assigns) do
  ~H"""
  <.icon_component icon={&Heroicons.Solid.lightning_bolt/1} text="Something" />
  """
end

defp icon_component(assigns) do
  ~H"""
  <%= @icon.(class: "h-4 w-4 ...") %> <%= @text %>
  """
end
```

But getting lots of warnings.

**Comment by soundmonster** [comment]
Having a way to parameterize the icon was very handy and feels like a valid use case, e.g. for generating navigation links.

**Comment by mveytsman** [comment]
I think you make a good point @soundmonster @joefreeman I'll cut a new version without the warnings

**Comment by mveytsman** [comment]
[0.3.1](https://hex.pm/packages/heroicons/0.3.1) is published on hex.pm!
